### PR TITLE
Email Fixes and Functionality

### LINKED ISSUE #200: Emailing Fixes and Functionality
We have emails implemented, but they do not match our data models. We also need to implement the proper email sending automations. 

Use the SendGrid credentials given to you; we will be sending real emails and automating them.

## Important notes
- Look at the email templates and make sure the types make sense to the data models we have.
- They might be a little off because it was made a while ago
- Use React Email CLI to test, edit the default props at the bottom of each template to see them in the local test.
- All email code is in `/email`

## Invite Emails (CreateAccountInvite, CreateAccountReminder)
- In `AccountManagement`, pending accounts can be sent reminders. This button is currently disabled. Enable the button and also add this functionality as an API endpoint at `POST /api/users/[userId]/reminder`.
  - It should create a new user invite that connects to the user. It should send out the reminder email template.
- Testing
  - Create a new admin account with your actual email. This tests the initial invitation email.
  - Then (before creating the account), send out a reminder to test the reminder email.

## DonorOfferCreated
- This email should be sent to all partners 
- Before getting to the functionality, in `app/donorOffers/create/page.tsx`, the `PartnerSearch` doesn't initially show the partners; it only shows them after typing something. This should not be the case and when the field is clicked, it should get the partners.
- When the donor offer is created, in the API route `POST /api/donorOffers`, an email should be sent to the partners that were apart of the donor offer.
- This email template needs to be changed as it. It should not include the items as a table, and should simply state that new items are avaliable for request as X donor has created an offer and have the button to view the donor offer at `/donorOffers/[donorOfferId]`.
  - There is also no point in showing the donor offer status as it will always be unfinalized when created
- Testing:
  - In the seed, modify one of the partners to have an email that you use (different email than the admin one)
  - Add this partner to the donor offer you're creating (use [this file](https://docs.google.com/spreadsheets/d/1sOxxWt1evo2CNwlOnQnt9ec5ruWygMo3/edit?usp=sharing&ouid=100320430120378150517&rtpof=true&sd=true) as the initial donor offer) and see if the email sends

## ExpiringItems
- This email will be on a cron and should email the admins about items that are expiring in the next month. 
- We use Netlify as our web hosting, so we will be creating Netlify scheduled functions. [Documentation](https://docs.netlify.com/build/functions/scheduled-functions/).
  - Look up how to make this work locally. 
  - For local development, you do not need to set up cron; you can use the Netlify CLI to run the function for testing. [Netlify Local Development Docs](https://docs.netlify.com/api-and-cli-guides/cli-guides/manage-functions/#invoke-functions-while-running-netlify-dev). You shouldn't need any sensitive information about the Netlify hosting, but if you do, let me know.
  - Set the schedule to daily
  - Create a function in `GeneralItemService` that gets the expiring items. There should be a datetime object parameter. 
    - It should return an array of general items where the donor offer is not archived and the expiration date is before the current datetime + passed in datetime object. 
    - Each general Item should also have two sum counts of line item quantity for unallocated (without an allocation attached) and allocated (with an allocation attached) items.
  - Send the expiring items email template to all staff (super admins, admins, and staff) 
- the email template is a little outdated. Do not include IDs for items. The table should also have two new columns that replace quantity: 'Unallocated Qty' and 'Distributed Qty'.
  - All of these quantity cells should have the respective line item quantity sum count.
- Testing:
  - Seed some unallocated and allocated items that are expiring soon
  - Use the Netlify CLI to call the function and send urself emails. (for testing, you can only include your email for sending instead of all the fake staff ones)

## ItemsVisibleNotification
- Rename and reword this email. We are overhauling how item distributions are handled so this needs to change too. 
- Instead of items becoming "visible," say that a new distribution of items have been assigned to you and to check out the distributions page to see them. Do not list out the items. Create a button that links to their distributions page ( for partners this is just '/')
- Lets name this template `NewDistribution`, rename the function in `EmailClient` accordingly.
- This will be implemented later, currently other tickets working on implementing distribution functionality.

## ResetPassword
- Testing:
  - Test out resetting your password on the admin account you created.

### PR DESCRIPTION
**Pull request by chrisgoggins**
## Description

Resolves #200 

## Checklist

- [x] The ticket is mentioned above
- [x] The changes fulfill the success criteria of the ticket
- [x] The changes were self-reviewed
- [x] A review was requested

### CODE REVIEW

File: src/app/api/users/route.ts [hunk 1]
```diff
@@ -54,14 +54,14 @@ export async function GET(request: NextRequest) {
...
+    // if (!session?.user) {
+    //   throw new AuthenticationError("Session required");
+    // }
 
-    if (!UserService.isAdmin(session.user.type)) {
-      throw new AuthorizationError("Must be STAFF, ADMIN, or SUPER_ADMIN");
-    }
+    // if (!UserService.isAdmin(session.user.type)) {
+    //   throw new AuthorizationError("Must be STAFF, ADMIN, or SUPER_ADMIN");
+    // }
```
Comment (chrisgoggins) [inline src/app/api/users/route.ts]: This stopped me from registering b/c I had no session, correct me if I am wrong with this logic

**Comment by chrisgoggins** [comment]
@greptileai addressed the critical issue

**Comment by chrisgoggins** [comment]
@greptileai consider the comment above and rerun a full check of the PR

File: src/app/api/users/route.ts (hunk 1 above)
Comment (Sectonic) [reply src/app/api/users/route.ts]: yeah this makes sense, you can remove that code.

File: src/app/api/users/[userId]/reminder/route.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+    _: NextRequest,
+  { params }: { params: Promise<{ userId: string }> }
+) {
+  try {
+    const session = await auth();
+    if (!session?.user) {
+      throw new AuthenticationError("Session required");
+    }
+
+    // TODO: what should the permissions be for this?
```
[the remark this answers is not in the document]
Comment (Sectonic) [reply src/app/api/users/[userId]/reminder/route.ts]: actually, only admins and above should be able to send these. Switch it to isAdmin

File: netlify/functions/expiringItems.ts [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+      unallocatedQuantity: item.unallocatedQuantity,
+      distributedQuantity: item.allocatedQuantity,
+    }));
+
+    const monthLabel = format(cutoff, "MMMM yyyy");
+
+    await EmailClient.sendItemsExpiring(staffUsers.map(s => s.email), {
+      month: monthLabel,
+      items: templateItems,
+    });
```
Comment (Sectonic) [inline netlify/functions/expiringItems.ts]: its not necessarily that the items are expiring THAT month. It's that they will expire in A month. A month label is unnecessary.
